logic [XLEN-1:0] int_registers [0:`NUM_REGS-1];
logic wb_halted;
logic fe_halted;
logic clk;
logic commit_valid;
logic [`REG_BITS-1:0] wb_rd;
logic [XLEN-1:0] wb_rd_value;
logic [XLEN-1:0] wb_pc;
instruction_t wb_instruction;
logic [31:0] csr_mstatus;
logic [31:0] csr_mtvec;
logic [31:0] csr_mepc;
logic [31:0] csr_mcause;
logic [31:0] csr_mtval;
